import _dk_core as core
from . import shader

DEPTH_FUNC_NEVER = 0
DEPTH_FUNC_ALWAYS = 1
DEPTH_FUNC_LESS = 2
DEPTH_FUNC_LESS_EQUAL = 3
DEPTH_FUNC_EQUAL = 4
DEPTH_FUNC_GREATER = 5
DEPTH_FUNC_GREATER_EQUAL = 6
DEPTH_FUNC_NOT_EQUAL = 7

UNIFORM_ID = shader.UNIFORM_ID
UNIFORM_TYPE = shader.UNIFORM_TYPE
STREAM_ID = shader.ATTRIBUTE_ID
STREAM_TYPE = shader.ATTRIBUTE_TYPE

VERTEX_SHADER = shader.TYPE_VERTEX_SHADER
FRAGMENT_SHADER = shader.TYPE_FRAGMENT_SHADER
GEOMETRY_SHADER = shader.TYPE_GEOMETRY_SHADER


Material = core.Material
