import _dk_core as core

#mesh draw-face
DRAW_FACE_NONE = 0
DRAW_FACE_CCW = 1       # default
DRAW_FACE_CW = 2
DRAW_FACE_BOTH = 3

#mesh primitive type
PRIMITIVE_POINTS = 1
PRIMITIVE_LINES = 2
PRIMITIVE_LINE_STRIP = 3
PRIMITIVE_LINE_LOOP = 4
PRIMITIVE_TRIANGLES = 5
PRIMITIVE_TRIANGLE_STRIP = 6
PRIMITIVE_TRIANGLE_FAN = 7
PRIMITIVE_LINES_ADJACENCY = 8
PRIMITIVE_LINE_STRIP_ADJACENCY = 9
PRIMITIVE_TRIANGLES_ADJACENCY = 10
PRIMITIVE_TRIANGLE_STRIP_ADJACENCY = 11


Mesh = core.Mesh
StaticMesh = core.StaticMesh
SkinMesh = core.SkinMesh
