
''' virtual key table
wrapper for native (C++) window's virtual-key-code
'''

def _enumIndex(_tmp = [0]):
    val = _tmp[0]
    _tmp[0] += 1
    return val

NONE = _enumIndex()
ESCAPE = _enumIndex()
F1 = _enumIndex()
F2 = _enumIndex()
F3 = _enumIndex()
F4 = _enumIndex()
F5 = _enumIndex()
F6 = _enumIndex()
F7 = _enumIndex()
F8 = _enumIndex()
F9 = _enumIndex()
F10 = _enumIndex()
F11 = _enumIndex()
F12 = _enumIndex()
F13 = _enumIndex()
F14 = _enumIndex()
F15 = _enumIndex()
F16 = _enumIndex()
F17 = _enumIndex()
F18 = _enumIndex()
F19 = _enumIndex()
F20 = _enumIndex()

NUM_0 = _enumIndex()
NUM_1 = _enumIndex()
NUM_2 = _enumIndex()
NUM_3 = _enumIndex()
NUM_4 = _enumIndex()
NUM_5 = _enumIndex()
NUM_6 = _enumIndex()
NUM_7 = _enumIndex()
NUM_8 = _enumIndex()
NUM_9 = _enumIndex()

A = _enumIndex()
B = _enumIndex()
C = _enumIndex()
D = _enumIndex()
E = _enumIndex()
F = _enumIndex()
G = _enumIndex()
H = _enumIndex()
I = _enumIndex()
J = _enumIndex()
K = _enumIndex()
L = _enumIndex()
M = _enumIndex()
N = _enumIndex()
O = _enumIndex()
P = _enumIndex()
Q = _enumIndex()
R = _enumIndex()
S = _enumIndex()
T = _enumIndex()
U = _enumIndex()
V = _enumIndex()
W = _enumIndex()
X = _enumIndex()
Y = _enumIndex()
Z = _enumIndex()

PERIOD = _enumIndex()
COMMA = _enumIndex()
SLASH = _enumIndex()
TAB = _enumIndex()
ACCENT_TILDE = _enumIndex()
BACKSPACE = _enumIndex()
SEMICOLON = _enumIndex()
QUOTE = _enumIndex()
BACKSLASH = _enumIndex()
EQUAL = _enumIndex()
HYPHEN = _enumIndex()
SPACE = _enumIndex()
OPEN_BRACKET = _enumIndex()
CLOSE_BRACKET = _enumIndex()
CAPS_LOCK = _enumIndex()

RETURN = _enumIndex()

FN = _enumIndex()
INSERT = _enumIndex()
HOME = _enumIndex()
PAGE_UP = _enumIndex()
PAGE_DOWN = _enumIndex()
END = _enumIndex()
DELETE = _enumIndex()

LEFT = _enumIndex()
RIGHT = _enumIndex()
UP = _enumIndex()
DOWN = _enumIndex()

LEFT_SHIFT = _enumIndex()
RIGHT_SHIFT = _enumIndex()
LEFT_OPTION = _enumIndex()
LEFT_ALT = LEFT_OPTION
RIGHT_OPTION = _enumIndex()
RIGHT_ALT = RIGHT_OPTION
LEFT_CONTROL = _enumIndex()
RIGHT_CONTROL = _enumIndex()
LEFT_COMMAND = _enumIndex()
RIGHT_COMMAND = _enumIndex()

PAD_0 = _enumIndex()
PAD_1 = _enumIndex()
PAD_2 = _enumIndex()
PAD_3 = _enumIndex()
PAD_4 = _enumIndex()
PAD_5 = _enumIndex()
PAD_6 = _enumIndex()
PAD_7 = _enumIndex()
PAD_8 = _enumIndex()
PAD_9 = _enumIndex()
ENTER = _enumIndex()
NUM_LOCK = _enumIndex()
PAD_SLASH = _enumIndex()
PAD_ASTERISK = _enumIndex()
PAD_PLUS = _enumIndex()
PAD_MINUS = _enumIndex()
PAD_EQUAL = _enumIndex()
PAD_PERIOD = _enumIndex()

_MAXVALUE = _enumIndex()

assert NONE == 0
assert _MAXVALUE == 111
